[build]
  # Commande de build
  command = "npm run build"
  
  # Dossier de publication
  publish = "build"
  
  # Variables d'environnement pour le build
  environment = { NODE_VERSION = "18" }

[build.processing]
  # Optimisation des images
  skip_processing = false

[build.processing.css]
  # Minification CSS
  bundle = true
  minify = true

[build.processing.js]
  # Minification JavaScript
  bundle = true
  minify = true

[build.processing.html]
  # Optimisation HTML
  pretty_urls = true

[build.processing.images]
  # Optimisation des images
  compress = true

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CSP (Content Security Policy)
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https: wss: https://*.infura.io https://*.alchemy.com https://*.etherscan.io https://api.coingecko.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """
    
    # Performance
    Cache-Control = "public, max-age=31536000, immutable"

# Headers spécifiques pour les assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour le HTML (pas de cache)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers pour le service worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Variables d'environnement pour la production
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# Variables d'environnement pour la prévisualisation
[context.deploy-preview.environment]
  NODE_ENV = "development"
  REACT_APP_ENV = "preview"

# Variables d'environnement pour les branches
[context.branch-deploy.environment]
  NODE_ENV = "development"
  REACT_APP_ENV = "staging"

# Fonctions Netlify (si nécessaire pour l'API)
[functions]
  directory = "netlify/functions"

# Plugins Netlify
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
    
  [plugins.inputs.settings]
    # Audit de performance
    performance = true
    accessibility = true
    best_practices = true
    seo = true
    pwa = true

# Plugin pour l'optimisation des images
[[plugins]]
  package = "netlify-plugin-image-optim"

# Plugin pour la compression
[[plugins]]
  package = "netlify-plugin-compress"
